# Undertow settings
server:
  port: ${SERVER_PORT:8080}
  undertow:
    threads:
      io: ${UNDERTOW_IO_THREADS:1}
      worker: ${UNDERTOW_WORKER_THREADS:8}
    buffer-size: ${UNDERTOW_BUFFER_SIZE:1024}

# Management settings
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    elasticsearch:
      enabled: false

# Logging settings
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
        security: INFO
        boot: INFO
      hibernate: INFO
    com:
      sample: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:100MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:50}

# Knife4j settings
knife4j:
  enable: true
  setting:
    enableOpenApi: false
    enableFooterCustom: true
    footerCustomContent: 版权所有 | Copyright 2022
  document:
    title: 在线API文档
    description: 学习项目
    version: 0.4.0
    developer:
      name: InCar
      url: https://github.com/aaric
      email: vipaaric@gmail.com

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: rocketmq-achieve
  cloud:
    stream:
      # BindingProperties
      bindings:
        output:
          destination: TopicTest
          content-type: text/plain
        input:
          destination: TopicTest
          content-type: text/plain
          group: GroupTest
#        output1:
#          destination: topic1
#          content-type: application/json
      # RocketMQBinderConfigurationProperties
#      rocketmq:
#        binder:
#          name-server: 127.0.0.1:9876
#          enable-msg-trace: false
#        bindings:
#          channel1:
#            producer:
#              group: GroupTest
#              sync: true
#            consumer:
#              tags: TagA || TagB
#              orderly: true

# RocketMQ settings
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: GroupTest
